import { Project, IdeaItem, ModuleReadiness } from "./types";

export const INITIAL_PROJECTS: Project[] = [
  {
    id: "proj-innovation-hub",
    name: "💻 Code of Innovation Hub",
    description: "Master workspace for tracking the design, electronics, fabrication, and smart systems of the Innovation Hub.",
    tags: [],
    modules: [
      { id: "mod-electronics", name: "Electronics", icon: "🔌", color: "#6366f1", owner: "Abdallah", readiness: "prototype" },
      { id: "mod-fabrication", name: "Fabrication", icon: "🔨", color: "#f59e0b", owner: "Alice", readiness: "bench-test", dependsOn: ["mod-electronics"] },
      { id: "mod-3dprinting", name: "3D Printing", icon: "🧱", color: "#06b6d4", owner: "Alice", readiness: "design" },
      { id: "mod-software", name: "Software", icon: "💻", color: "#10b981", owner: "Abdallah", readiness: "prototype", dependsOn: ["mod-electronics"] },
      { id: "mod-safety", name: "Safety", icon: "🛡️", color: "#f43f5e", owner: "Sallam", readiness: "integrated" },
    ],
    goals: [
      {
        id: "goal-demo",
        title: "Deliver a working Innovation Hub demo build",
        specific: "Integrate the electronics, firmware, and fabricated chassis into one demoable unit.",
        measurable: "All 5 modules reach at least 'Integrated' readiness and 90% of tasks complete.",
        achievable: "Current team of 3 with existing hardware; no new procurement required.",
        relevant: "Needed for the end-of-term Innovation Hub showcase.",
        timeBound: "2026-08-15",
        progress: 40,
      },
      {
        id: "goal-safety",
        title: "Pass the lab safety audit",
        specific: "Close all Safety-module tasks and document compliance for each workstation.",
        measurable: "Zero open Safety tasks and a signed checklist per station.",
        achievable: "Sallam owns Safety; most items are documentation.",
        relevant: "Required before the lab can host external visitors.",
        timeBound: "2026-07-31",
        progress: 65,
        moduleIds: ["mod-safety"],
      },
    ],
    columns: [
      { id: "col-todo", title: "Not Started", color: "#64748b" },
      { id: "col-progress", title: "In Progress", color: "#3b82f6" },
      { id: "col-blocked", title: "Blocked", color: "#f43f5e" },
      { id: "col-done", title: "Completed", color: "#10b981" },
    ],
    teams: [
      { id: "team-sw", name: "Software Team", description: "Cloud services, dynamic dashboards, and embedded firmware code." },
      { id: "team-hw", name: "Hardware & IoT", description: "Microcontrollers, sensor calibration, and radio transceiver grids." },
      { id: "team-fab", name: "Fabrication & Design", description: "CAD design, laser alignments, and 3D printing assemblies." },
      { id: "team-ops", name: "Operations & Safety", description: "Workspace regulatory guidelines, safety logs, and asset logging." }
    ],
    members: [
      { id: "m-abdallah", name: "Abdallah", role: "Innovation Lead", email: "abdallah.salaheldean@gmail.com", teamId: "team-sw", avatar: "A", bg: "bg-indigo-600" },
      { id: "m-sallam", name: "Sallam", role: "Systems Engineer", email: "sallam.workspace@gmail.com", teamId: "team-hw", avatar: "S", bg: "bg-blue-600" },
      { id: "m-alice", "name": "Alice", role: "Lab Contributor", email: "alice@workspace.io", teamId: "team-fab", avatar: "A", bg: "bg-emerald-600" },
      { id: "m-bob", "name": "Bob", "role": "Lab Contributor", email: "bob@workspace.io", teamId: "team-hw", avatar: "B", bg: "bg-indigo-500" },
      { id: "m-charlie", "name": "Charlie", "role": "Lab Contributor", email: "charlie@workspace.io", teamId: "team-sw", avatar: "C", bg: "bg-slate-700" },
      { id: "m-diana", "name": "Diana", "role": "Lab Contributor", email: "diana@workspace.io", teamId: "team-ops", avatar: "D", bg: "bg-amber-600" }
    ],
    ideas: [
    {
        "id": "idea-1",
        "timeHorizon": "Next Month",
        "title": "Define policies & entities",
        "description": "",
        "targetDate": "",
        "status": "ready",
        "priority": "High",
        "zone": "Zone 1: Ready to Start (Important and Urgent)"
    },
    {
        "id": "idea-2",
        "timeHorizon": "Next Month",
        "title": "Build fixed-asset report (safety focus)",
        "description": "",
        "targetDate": "",
        "status": "ready",
        "priority": "High",
        "zone": "Zone 1: Ready to Start (Important and Urgent)"
    },
    {
        "id": "idea-3",
        "timeHorizon": "Next Month",
        "title": "Roll out QR-code system for assets",
        "description": "",
        "targetDate": "",
        "status": "ready",
        "priority": "High",
        "zone": "Zone 1: Ready to Start (Important and Urgent)"
    },
    {
        "id": "idea-4",
        "timeHorizon": "Next Month",
        "title": "Set up electronic / general workbench",
        "description": "",
        "targetDate": "",
        "status": "ready",
        "priority": "High",
        "zone": "Zone 1: Ready to Start (Important and Urgent)"
    },
    {
        "id": "idea-5",
        "timeHorizon": "Someday",
        "title": "Safety: manufacturing lab & all equipment",
        "description": "",
        "targetDate": "",
        "status": "hold",
        "priority": "Low",
        "zone": "Zone 4: On Hold / Wishlist (Not Important and Not Urgent)"
    },
    {
        "id": "idea-6",
        "timeHorizon": "Someday",
        "title": "CNC Router - register as fixed asset",
        "description": "",
        "targetDate": "",
        "status": "hold",
        "priority": "Low",
        "zone": "Zone 4: On Hold / Wishlist (Not Important and Not Urgent)"
    },
    {
        "id": "idea-7",
        "timeHorizon": "Someday",
        "title": "Set up data logger",
        "description": "",
        "targetDate": "",
        "status": "hold",
        "priority": "Low",
        "zone": "Zone 4: On Hold / Wishlist (Not Important and Not Urgent)"
    },
    {
        "id": "idea-8",
        "timeHorizon": "Someday",
        "title": "Innovation content on LinkedIn",
        "description": "",
        "targetDate": "",
        "status": "hold",
        "priority": "Low",
        "zone": "Zone 4: On Hold / Wishlist (Not Important and Not Urgent)"
    },
    {
        "id": "idea-9",
        "timeHorizon": "Someday",
        "title": "Document sequence of operation",
        "description": "",
        "targetDate": "",
        "status": "hold",
        "priority": "Low",
        "zone": "Zone 4: On Hold / Wishlist (Not Important and Not Urgent)"
    },
    {
        "id": "idea-10",
        "timeHorizon": "Someday",
        "title": "Project: Mobile robot",
        "description": "",
        "targetDate": "",
        "status": "hold",
        "priority": "Low",
        "zone": "Zone 4: On Hold / Wishlist (Not Important and Not Urgent)"
    },
    {
        "id": "idea-11",
        "timeHorizon": "Someday",
        "title": "Project: Tesla coil",
        "description": "",
        "targetDate": "",
        "status": "hold",
        "priority": "Low",
        "zone": "Zone 4: On Hold / Wishlist (Not Important and Not Urgent)"
    },
    {
        "id": "idea-12",
        "timeHorizon": "Someday",
        "title": "Project: 3D Watcher",
        "description": "",
        "targetDate": "",
        "status": "hold",
        "priority": "Low",
        "zone": "Zone 4: On Hold / Wishlist (Not Important and Not Urgent)"
    },
    {
        "id": "idea-13",
        "timeHorizon": "Someday",
        "title": "Project: [unclear name]",
        "description": "",
        "targetDate": "",
        "status": "hold",
        "priority": "Low",
        "zone": "Zone 4: On Hold / Wishlist (Not Important and Not Urgent)"
    },
    {
        "id": "idea-14",
        "timeHorizon": "Someday",
        "title": "Project: Tool Watcher",
        "description": "",
        "targetDate": "",
        "status": "hold",
        "priority": "Low",
        "zone": "Zone 4: On Hold / Wishlist (Not Important and Not Urgent)"
    },
    {
        "id": "idea-15",
        "timeHorizon": "Someday",
        "title": "Project: Motor control",
        "description": "",
        "targetDate": "",
        "status": "hold",
        "priority": "Low",
        "zone": "Zone 4: On Hold / Wishlist (Not Important and Not Urgent)"
    },
    {
        "id": "idea-16",
        "timeHorizon": "Someday",
        "title": "Project: [unclear name]",
        "description": "",
        "targetDate": "",
        "status": "hold",
        "priority": "Low",
        "zone": "Zone 4: On Hold / Wishlist (Not Important and Not Urgent)"
    },
    {
        "id": "idea-17",
        "timeHorizon": "Someday",
        "title": "Project: [unclear name]",
        "description": "",
        "targetDate": "",
        "status": "hold",
        "priority": "Low",
        "zone": "Zone 4: On Hold / Wishlist (Not Important and Not Urgent)"
    },
    {
        "id": "idea-18",
        "timeHorizon": "Someday",
        "title": "Project: Cold welding + [unclear]",
        "description": "",
        "targetDate": "",
        "status": "hold",
        "priority": "Low",
        "zone": "Zone 4: On Hold / Wishlist (Not Important and Not Urgent)"
    },
    {
        "id": "idea-19",
        "timeHorizon": "Someday",
        "title": "Project: Inverter",
        "description": "",
        "targetDate": "",
        "status": "hold",
        "priority": "Low",
        "zone": "Zone 4: On Hold / Wishlist (Not Important and Not Urgent)"
    },
    {
        "id": "idea-20",
        "timeHorizon": "Someday",
        "title": "Project: Automate Visualizer [unclear]",
        "description": "",
        "targetDate": "",
        "status": "hold",
        "priority": "Low",
        "zone": "Zone 4: On Hold / Wishlist (Not Important and Not Urgent)"
    },
    {
        "id": "idea-21",
        "timeHorizon": "Someday",
        "title": "Project: PID controller",
        "description": "",
        "targetDate": "",
        "status": "hold",
        "priority": "Low",
        "zone": "Zone 4: On Hold / Wishlist (Not Important and Not Urgent)"
    },
    {
        "id": "idea-22",
        "timeHorizon": "Someday",
        "title": "Project: [unclear] printer",
        "description": "",
        "targetDate": "",
        "status": "hold",
        "priority": "Low",
        "zone": "Zone 4: On Hold / Wishlist (Not Important and Not Urgent)"
    },
    {
        "id": "idea-23",
        "timeHorizon": "Someday",
        "title": "Tool-handout system & project",
        "description": "",
        "targetDate": "",
        "status": "building",
        "priority": "Medium",
        "zone": "Zone 2: Building / Refining (Important and Not Urgent)"
    },
    {
        "id": "idea-24",
        "timeHorizon": "Someday",
        "title": "Email automation + work dashboard + decision log",
        "description": "",
        "targetDate": "",
        "status": "building",
        "priority": "Medium",
        "zone": "Zone 2: Building / Refining (Important and Not Urgent)"
    },
    {
        "id": "idea-25",
        "timeHorizon": "Someday",
        "title": "Establish PCB production line",
        "description": "",
        "targetDate": "",
        "status": "building",
        "priority": "Medium",
        "zone": "Zone 2: Building / Refining (Important and Not Urgent)"
    },
    {
        "id": "idea-26",
        "timeHorizon": "Someday",
        "title": "Run LinkedIn sessions",
        "description": "",
        "targetDate": "",
        "status": "building",
        "priority": "Medium",
        "zone": "Zone 2: Building / Refining (Important and Not Urgent)"
    },
    {
        "id": "idea-27",
        "timeHorizon": "Someday",
        "title": "KPI emails + Microsoft Forms",
        "description": "",
        "targetDate": "",
        "status": "building",
        "priority": "Medium",
        "zone": "Zone 2: Building / Refining (Important and Not Urgent)"
    },
    {
        "id": "idea-28",
        "timeHorizon": "Someday",
        "title": "Odoo crash course - Inventory",
        "description": "",
        "targetDate": "",
        "status": "building",
        "priority": "Medium",
        "zone": "Zone 2: Building / Refining (Important and Not Urgent)"
    },
    {
        "id": "idea-29",
        "timeHorizon": "Next Month",
        "title": "Resolve chair problem",
        "description": "",
        "targetDate": "",
        "status": "planning",
        "priority": "High",
        "zone": "Zone 3: Planning / Defining (Not Important and Urgent)"
    },
    {
        "id": "idea-30",
        "timeHorizon": "Next Month",
        "title": "PCB session - green light & prep",
        "description": "",
        "targetDate": "",
        "status": "planning",
        "priority": "High",
        "zone": "Zone 3: Planning / Defining (Not Important and Urgent)"
    },
    {
        "id": "idea-31",
        "timeHorizon": "Next Month",
        "title": "Add gamification to Project Map",
        "description": "",
        "targetDate": "",
        "status": "ready",
        "priority": "High",
        "zone": "Zone 1: Ready to Start (Important and Urgent)"
    },
    {
        "id": "idea-32",
        "timeHorizon": "Next Month",
        "title": "Action item: Ahmed Ibrahim",
        "description": "",
        "targetDate": "",
        "status": "ready",
        "priority": "High",
        "zone": "Zone 1: Ready to Start (Important and Urgent)"
    },
    {
        "id": "idea-33",
        "timeHorizon": "Next Month",
        "title": "3D Printers Amr Safwat Report",
        "description": "",
        "targetDate": "",
        "status": "ready",
        "priority": "High",
        "zone": "Zone 1: Ready to Start (Important and Urgent)"
    },
    {
        "id": "idea-34",
        "timeHorizon": "Someday",
        "title": "Project : Radio TA5767",
        "description": "",
        "targetDate": "",
        "status": "hold",
        "priority": "Low",
        "zone": "Zone 4: On Hold / Wishlist (Not Important and Not Urgent)"
    },
    {
        "id": "idea-35",
        "timeHorizon": "Next Month",
        "title": "Battries Sessions",
        "description": "",
        "targetDate": "2026-07-16",
        "status": "planning",
        "priority": "Medium",
        "zone": "Zone 3: Planning / Defining (Not Important and Urgent)"
    }
],
    tasks: [
{
            "id": "TASK-003",
            "title": "Innovation Hub Visualizer Kit",
            "description": "",
            "status": "col-done",
            "priority": "medium",
            "assignee": "Abdallah",
            "startDate": "2026-06-19",
            "dueDate": "2026-06-19",
            "estimatedHours": 5,
            "actualHours": 5,
            "location": "Office/Remote",
            "notes": "Logged from Daily Logs board",
            "subtasks": [],
            "comments": [],
            "createdAt": "2026-06-19",
            "tags": []
      },
      {
            "id": "TASK-006",
            "title": "Test Run v0.2",
            "description": "",
            "status": "col-done",
            "priority": "urgent",
            "assignee": "Abdallah",
            "startDate": "2026-06-20",
            "dueDate": "2026-06-20",
            "estimatedHours": 1,
            "actualHours": 1,
            "location": "Office/Remote",
            "notes": "[At 02:00 AM] Stest run of the visualizer V0.2",
            "subtasks": [],
            "comments": [],
            "createdAt": "2026-06-20",
            "tags": []
      },
      {
            "id": "TASK-007",
            "title": "ECE Measurement Test Out",
            "description": "",
            "status": "col-done",
            "priority": "medium",
            "assignee": "Sallam",
            "startDate": "2026-06-20",
            "dueDate": "2026-06-20",
            "estimatedHours": 8,
            "actualHours": 8,
            "location": "Office/Remote",
            "notes": "[At 09:00 AM] ECE Department Measurement Testout Sessions",
            "subtasks": [],
            "comments": [],
            "createdAt": "2026-06-20",
            "tags": []
      },
      {
            "id": "TASK-008",
            "title": "Tasneem 3D Printing",
            "description": "",
            "status": "col-done",
            "priority": "medium",
            "assignee": "Unassigned",
            "startDate": "2026-06-21",
            "dueDate": "2026-06-21",
            "estimatedHours": 1,
            "actualHours": 4,
            "location": "Office/Remote",
            "notes": "[At 09:00 AM] \n-D:\\Abdallah Salaheldean\\Innovation\\3D-Printing\\Tasneem Tarek Abdelkereem\\21-6-2026\\New Print 2023\\200 mm\\0_Taber ratio",
            "subtasks": [],
            "comments": [],
            "createdAt": "2026-06-21",
            "tags": []
      },
      {
            "id": "TASK-009",
            "title": "3D Printing Variable Layer Height",
            "description": "",
            "status": "col-done",
            "priority": "medium",
            "assignee": "Unassigned",
            "startDate": "2026-06-21",
            "dueDate": "2026-06-21",
            "estimatedHours": 1,
            "actualHours": 1,
            "location": "Office/Remote",
            "notes": "[At 09:00 AM] - https://www.youtube.com/shorts/jVD0irMC4L8\n\n- Find a Model to try it out - Done\n\n- https://www.youtube.com/watch?v=gTQg5fSs_as&t=39s",
            "subtasks": [],
            "comments": [],
            "createdAt": "2026-06-21",
            "tags": []
      },
      {
            "id": "TASK-010",
            "title": "3D Printing Thermal Tower",
            "description": "",
            "status": "col-done",
            "priority": "medium",
            "assignee": "Unassigned",
            "startDate": "2026-06-21",
            "dueDate": "2026-06-21",
            "estimatedHours": 1,
            "actualHours": 1,
            "location": "Office/Remote",
            "notes": "[At 09:00 AM] - https://www.youtube.com/watch?v=WR2tRwzFlq0&t=83s\n-https://www.printables.com/model/20652-temp-tower-pla-petg-absasa-for-prusa-mini-mk3s-and",
            "subtasks": [],
            "comments": [],
            "createdAt": "2026-06-21",
            "tags": []
      },
      {
            "id": "TASK-011",
            "title": "Masters",
            "description": "",
            "status": "col-done",
            "priority": "urgent",
            "assignee": "Sallam",
            "startDate": "2026-06-19",
            "dueDate": "2026-06-22",
            "estimatedHours": 10,
            "actualHours": 0,
            "location": "Remote",
            "notes": "[At 09:00 AM] ",
            "subtasks": [],
            "comments": [],
            "createdAt": "2026-06-19",
            "tags": []
      },
      {
            "id": "TASK-012",
            "title": "3DP G-Code",
            "description": "",
            "status": "col-done",
            "priority": "medium",
            "assignee": "Abdallah",
            "startDate": "2026-06-22",
            "dueDate": "2026-06-23",
            "estimatedHours": 4,
            "actualHours": 4,
            "location": "Office/Remote",
            "notes": "[At 09:00 AM] Eng. Shad - Check that the G Code matches the prusa\n\n# ROLE\nYou are a G-code verification assistant. Your job is to examine a G-code file and\ndetermine whether it is safe to print on my specific 3D printer. Be precise and\nconservative: when something is ambiguous or missing, say so rather than assuming.\n\n# MY PRINTER (the target)\n- Model: Prusa i3 MK3S+ (MK3S-compatible G-code is fine)\n- Nozzle: 0.4 mm\n- Build volume: 250 (X) × 210 (Y) × 210 (Z) mm\n- Firmware: Marlin (Prusa fork)\n- File format expected: plain-text .gcode (NOT binary .bgcode)\n\n# WHAT TO DO\nRead the file's header/config comments AND scan the actual motion commands.\nDo not rely only on the comment block — verify against the real G-code body.\nThen run every check below and report findings.\n\n# HARD RULES (a FAIL on any of these = \"DO NOT PRINT\")\n1. NOZZLE: Find nozzle_diameter. If it is not 0.4 mm, FAIL.\n2. BUILD VOLUME: Scan all X/Y/Z coordinates in the motion commands. If any\n   X > 250, Y > 210, or Z > 210, the model won't fit — FAIL. Report the max\n   X, Y, Z actually reached.\n3. FLAVOR: Confirm the G-code flavor is Marlin. If it is Klipper, RepRap/Duet,\n   Bambu/X1-specific, or anything non-Marlin, FAIL.\n4. PRINTER MODEL: Look for printer_model / compatible printers / settings IDs.\n   - If it names a Prusa MK3S/MK3S+, PASS this check.\n   - If it names a DIFFERENT printer (MK4, MINI, Ender, Bambu, etc.), FAIL.\n5. FILE TYPE: If the content is binary/garbled rather than readable text\n   commands, it may be .bgcode — FAIL and tell me to re-export as plain G-code.\n6. UNSUPPORTED COMMANDS: Flag any machine-specific codes the Prusa Marlin\n   firmware would not understand — e.g. AMS/multi-material toolchanges, vendor-\n   only M-codes (Bambu, Klipper macros). Note them. Core moves (G0/G1/G2/G3,\n   G28, G29, M104/M109/M140/M190, M106) are all fine.\n\n# SAFETY CHECKS (a problem here = \"PRINT WITH CAUTION\", not an automatic fail)\n7. TEMPERATURES: Report nozzle and bed temps (M104/M109/M140/M190). Flag if\n   nozzle > 300 °C or bed > 120 °C, or if temps look wrong for the stated\n   filament (e.g. PLA above ~230 °C, or 0 °C where heat is expected).\n8. MODEL-CHECK LINE: Note whether an M862.3 model-check line is present.\n   - Present and matching MK3S = good, the printer will self-verify.\n   - ABSENT (common when sliced in non-Prusa slicers like Bambu Studio or Cura)\n     = the printer will NOT verify the model itself, so I'm trusting the profile.\n     Tell me this so I watch the first layer.\n9. START/END SEQUENCE: Confirm there's a sane startup (home G28, usually mesh\n   leveling G29, a purge/intro line) and a sane ending (turn off heaters M104 S0\n   / M140 S0, fan off M107, park, disable motors M84). Flag if missing.\n10. BED ORIGIN / OFFSETS: Note if coordinates look shifted off the bed or use an\n    unexpected origin that could cause the nozzle to crash or print off-plate.\n\n# SLICER NOTE\nIdentify which slicer and version produced the file (from the header). It's OK\nif it's not PrusaSlicer (e.g. Bambu Studio or Cura targeting a Prusa profile) —\njust confirm the profile/settings actually target the MK3S and the rules above pass.\n\n# OUTPUT FORMAT (use exactly this)\n**VERDICT:** ✅ SAFE TO PRINT  /  ⚠️ PRINT WITH CAUTION  /  ❌ DO NOT PRINT\n\n**Sliced by:** <slicer + version>\n**Target printer in file:** <printer_model found>\n**Nozzle:** <value>\n**Max dimensions reached:** X__ Y__ Z__ (vs limits 250×210×210)\n**Flavor:** <Marlin / other>\n**Temps:** nozzle __°C, bed __°C  (filament: __)\n**M862.3 model check:** present / absent\n**Start/End sequence:** ok / issues\n\n**Why:** <2–4 sentence plain explanation of the verdict>\n**Watch out for:** <anything I should monitor, or \"nothing — looks clean\">",
            "subtasks": [],
            "comments": [],
            "createdAt": "2026-06-22",
            "tags": []
      },
      {
            "id": "TASK-013",
            "title": "Robotino Day 2 Report",
            "description": "",
            "status": "col-done",
            "priority": "medium",
            "assignee": "Unassigned",
            "startDate": "2026-06-23",
            "dueDate": "2026-06-24",
            "estimatedHours": 1,
            "actualHours": 1,
            "location": "Office/Remote",
            "notes": "[At 09:00 AM] Write a report and a LinkedIn link here",
            "subtasks": [],
            "comments": [],
            "createdAt": "2026-06-23",
            "tags": []
      },
      {
            "id": "TASK-014",
            "title": "Robotino Sessions",
            "description": "",
            "status": "col-done",
            "priority": "medium",
            "assignee": "Unassigned",
            "startDate": "2026-06-22",
            "dueDate": "2026-06-25",
            "estimatedHours": 32,
            "actualHours": 8,
            "location": "Office/Remote",
            "notes": "[At 09:00 AM] Logged from Daily Logs board",
            "subtasks": [],
            "comments": [],
            "createdAt": "2026-06-22",
            "tags": []
      },
      {
            "id": "TASK-015",
            "title": "shahd printing  files",
            "description": "",
            "status": "col-done",
            "priority": "medium",
            "assignee": "Unassigned",
            "startDate": "2026-06-23",
            "dueDate": "2026-06-23",
            "estimatedHours": 3,
            "actualHours": 3,
            "location": "Office/Remote",
            "notes": "[At 09:00 AM] together\n\nD:\\sallam\\shahad\\G-codes for printing\nD638 Type 1 _50_Cubic_PLA+_31m31s_7.94g.gcode",
            "subtasks": [],
            "comments": [],
            "createdAt": "2026-06-23",
            "tags": []
      },
      {
            "id": "TASK-016",
            "title": "Tasneem 3D printing 200 mm",
            "description": "",
            "status": "col-done",
            "priority": "low",
            "assignee": "Unassigned",
            "startDate": "2026-06-23",
            "dueDate": "2026-06-24",
            "estimatedHours": 12,
            "actualHours": 12,
            "location": "Office/Remote",
            "notes": "[At 09:00 AM] D:\\Abdallah Salaheldean\\Innovation\\3D-Printing\\Tasneem Tarek Abdelkereem\\21-6-2026\\New Print 2023\\200 mm\\0.2_Taber ratio",
            "subtasks": [],
            "comments": [],
            "createdAt": "2026-06-23",
            "tags": []
      },
      {
            "id": "TASK-017",
            "title": "Entity Survey : Eltoukhy Learning Factory",
            "description": "",
            "status": "col-done",
            "priority": "medium",
            "assignee": "Abdallah",
            "startDate": "2026-06-26",
            "dueDate": "2026-06-26",
            "estimatedHours": 4,
            "actualHours": 4,
            "location": "Office/Remote",
            "notes": "[At 10:00 AM] Logged from Daily Logs board",
            "subtasks": [],
            "comments": [],
            "createdAt": "2026-06-26",
            "tags": []
      },
      {
            "id": "TASK-018",
            "title": "Entity Survey : Ain Shams University iHub",
            "description": "",
            "status": "col-done",
            "priority": "medium",
            "assignee": "Abdallah",
            "startDate": "2026-06-27",
            "dueDate": "2026-06-28",
            "estimatedHours": 4,
            "actualHours": 4,
            "location": "Office/Remote",
            "notes": "[At 09:00 AM] Logged from Daily Logs board",
            "subtasks": [],
            "comments": [],
            "createdAt": "2026-06-27",
            "tags": []
      },
      {
            "id": "TASK-019",
            "title": "3D Printers Amr Safwat Report",
            "description": "",
            "status": "col-progress",
            "priority": "medium",
            "assignee": "Sallam",
            "startDate": "2026-06-28",
            "dueDate": "2026-06-28",
            "estimatedHours": 4,
            "actualHours": 4,
            "location": "Office/Remote",
            "notes": "[At 10:45 AM] Logged from Daily Logs board",
            "subtasks": [],
            "comments": [],
            "createdAt": "2026-06-28",
            "tags": []
      },
      {
            "id": "TASK-020",
            "title": "3D Printing Shahd",
            "description": "",
            "status": "col-done",
            "priority": "medium",
            "assignee": "Unassigned",
            "startDate": "2026-06-28",
            "dueDate": "2026-06-28",
            "estimatedHours": 4,
            "actualHours": 4,
            "location": "Office/Remote",
            "notes": "[At 09:00 AM] D:\\Abdallah Salaheldean\\Innovation\\3D-Printing\\Shahd\\25-06-2026\\1_D638 Type 1 _50_Grid_PLA+_32m14s_7.93g",
            "subtasks": [],
            "comments": [],
            "createdAt": "2026-06-28",
            "tags": []
      },
      {
            "id": "TASK-021",
            "title": "3D Printing Egals",
            "description": "",
            "status": "col-done",
            "priority": "medium",
            "assignee": "Unassigned",
            "startDate": "2026-06-28",
            "dueDate": "2026-06-28",
            "estimatedHours": 4,
            "actualHours": 4,
            "location": "Office/Remote",
            "notes": "[At 09:00 AM] D:\\Abdallah Salaheldean\\Innovation\\3D-Printing\\Eagles\\28-06-2026\\air cover 1 p1",
            "subtasks": [],
            "comments": [],
            "createdAt": "2026-06-28",
            "tags": []
      },
      {
            "id": "TASK-022",
            "title": "Civil Shaker Request and Foam Cutting",
            "description": "",
            "status": "col-done",
            "priority": "medium",
            "assignee": "Unassigned",
            "startDate": "2026-06-28",
            "dueDate": "2026-06-28",
            "estimatedHours": 1,
            "actualHours": 1,
            "location": "Office/Remote",
            "notes": "[At 04:00 PM] Logged from Daily Logs board",
            "subtasks": [],
            "comments": [],
            "createdAt": "2026-06-28",
            "tags": []
      },
      {
            "id": "TASK-023",
            "title": "Mohannad 3D Printing",
            "description": "",
            "status": "col-progress",
            "priority": "medium",
            "assignee": "Unassigned",
            "startDate": "2026-06-29",
            "dueDate": "2026-06-29",
            "estimatedHours": 4,
            "actualHours": 4,
            "location": "Office/Remote",
            "notes": "[At 10:00 AM] Logged from Daily Logs board",
            "subtasks": [],
            "comments": [],
            "createdAt": "2026-06-29",
            "tags": []
      },
      {
            "id": "TASK-024",
            "title": "Shahd 3D Printing",
            "description": "",
            "status": "col-done",
            "priority": "medium",
            "assignee": "Unassigned",
            "startDate": "2026-06-29",
            "dueDate": "2026-06-29",
            "estimatedHours": 4,
            "actualHours": 4,
            "location": "Office/Remote",
            "notes": "[At 09:00 AM] D:\\Abdallah Salaheldean\\Innovation\\3D-Printing\\Shahd\\25-06-2026\\2_D638 Type 1 _50_Honeycomb_PLA+_51m11s_8.43g.gcode",
            "subtasks": [],
            "comments": [],
            "createdAt": "2026-06-29",
            "tags": []
      },
      {
            "id": "TASK-025",
            "title": "Eman/David Thermal Device",
            "description": "",
            "status": "col-blocked",
            "priority": "medium",
            "assignee": "Sallam",
            "startDate": "2026-06-29",
            "dueDate": "2026-06-29",
            "estimatedHours": 4,
            "actualHours": 4,
            "location": "Office/Remote",
            "notes": "[At 10:00 AM] Logged from Daily Logs board",
            "subtasks": [],
            "comments": [],
            "createdAt": "2026-06-29",
            "tags": []
      },
      {
            "id": "TASK-026",
            "title": "ESP-Cam 3D Printer and Tools Monitoring",
            "description": "",
            "status": "col-todo",
            "priority": "medium",
            "assignee": "Abdallah",
            "startDate": "2026-06-29",
            "dueDate": "2026-06-29",
            "estimatedHours": 4,
            "actualHours": 4,
            "location": "Office/Remote",
            "notes": "[At 09:00 AM] Logged from Daily Logs board",
            "subtasks": [],
            "comments": [],
            "createdAt": "2026-06-29",
            "tags": []
      },
      {
            "id": "TASK-027",
            "title": "Electronic Workbench",
            "description": "",
            "status": "col-progress",
            "priority": "medium",
            "assignee": "Abdallah",
            "startDate": "2026-06-29",
            "dueDate": "2026-06-29",
            "estimatedHours": 4,
            "actualHours": 4,
            "location": "Office/Remote",
            "notes": "[At 09:00 AM] Logged from Daily Logs board",
            "subtasks": [],
            "comments": [],
            "createdAt": "2026-06-29",
            "tags": []
      },
      {
            "id": "TASK-028",
            "title": "Ahmed Ibrahim تصفية العهدة",
            "description": "",
            "status": "col-blocked",
            "priority": "medium",
            "assignee": "Unassigned",
            "startDate": "2026-06-29",
            "dueDate": "2026-06-29",
            "estimatedHours": 4,
            "actualHours": 4,
            "location": "Office/Remote",
            "notes": "[At 10:00 AM] Logged from Daily Logs board",
            "subtasks": [],
            "comments": [],
            "createdAt": "2026-06-29",
            "tags": []
      },
      {
            "id": "TASK-029",
            "title": "Claude Code Vercel Visualizer Web-Kit",
            "description": "",
            "status": "col-progress",
            "priority": "medium",
            "assignee": "Abdallah",
            "startDate": "2026-06-19",
            "dueDate": "2026-06-19",
            "estimatedHours": 10,
            "actualHours": 0,
            "location": "Remote",
            "notes": "[At 09:00 AM] ",
            "subtasks": [],
            "comments": [],
            "createdAt": "2026-06-19",
            "tags": []
      },
      {
            "id": "TASK-030",
            "title": "Eagles Printing",
            "description": "",
            "status": "col-done",
            "priority": "medium",
            "assignee": "Unassigned",
            "startDate": "2026-07-05",
            "dueDate": "2026-07-05",
            "estimatedHours": 3,
            "actualHours": 3,
            "location": "Office/Remote",
            "notes": "[At 09:00 AM] Logged from Daily Logs board",
            "subtasks": [],
            "comments": [],
            "createdAt": "2026-07-05",
            "tags": []
      },
      {
            "id": "TASK-031",
            "title": "HPDE Manfacting With Civil Eng. Mohammed Mohsen",
            "description": "",
            "status": "col-progress",
            "priority": "medium",
            "assignee": "Unassigned",
            "startDate": "2026-07-05",
            "dueDate": "2026-07-05",
            "estimatedHours": 4,
            "actualHours": 4,
            "location": "Office/Remote",
            "notes": "[At 01:00 PM] Logged from Daily Logs board",
            "subtasks": [],
            "comments": [],
            "createdAt": "2026-07-05",
            "tags": []
      },
      {
            "id": "TASK-032",
            "title": "Prusa Thermal Modle Error",
            "description": "",
            "status": "col-done",
            "priority": "medium",
            "assignee": "Abdallah",
            "startDate": "2026-07-05",
            "dueDate": "2026-07-05",
            "estimatedHours": 4,
            "actualHours": 4,
            "location": "Office/Remote",
            "notes": "[At 09:00 AM] Logged from Daily Logs board",
            "subtasks": [],
            "comments": [],
            "createdAt": "2026-07-05",
            "tags": []
      },
      {
            "id": "TASK-033",
            "title": "Summer Workshop (PCB)",
            "description": "",
            "status": "col-todo",
            "priority": "medium",
            "assignee": "Unassigned",
            "startDate": "2026-07-27",
            "dueDate": "2026-07-27",
            "estimatedHours": 4,
            "actualHours": 4,
            "location": "Office/Remote",
            "notes": "[At 10:00 AM] Logged from Daily Logs board",
            "subtasks": [],
            "comments": [],
            "createdAt": "2026-07-27",
            "tags": []
      },
      {
            "id": "TASK-034",
            "title": "Orentation session (For Innovaton Hub) and Quizz",
            "description": "",
            "status": "col-todo",
            "priority": "medium",
            "assignee": "Unassigned",
            "startDate": "2026-08-04",
            "dueDate": "2026-08-04",
            "estimatedHours": 4,
            "actualHours": 4,
            "location": "Office/Remote",
            "notes": "[At 10:00 AM] Logged from Daily Logs board",
            "subtasks": [],
            "comments": [],
            "createdAt": "2026-08-04",
            "tags": []
      },
      {
            "id": "TASK-035",
            "title": "System for story when the student enter the innovation till he leaves",
            "description": "",
            "status": "col-todo",
            "priority": "medium",
            "assignee": "Unassigned",
            "startDate": "2026-08-04",
            "dueDate": "2026-08-04",
            "estimatedHours": 4,
            "actualHours": 4,
            "location": "Office/Remote",
            "notes": "[At 10:00 AM] Logged from Daily Logs board",
            "subtasks": [],
            "comments": [],
            "createdAt": "2026-08-04",
            "tags": []
      },
      {
            "id": "TASK-036",
            "title": "Reply for laser cutting email",
            "description": "",
            "status": "col-progress",
            "priority": "medium",
            "assignee": "Sallam",
            "startDate": "2026-07-08",
            "dueDate": "2026-07-08",
            "estimatedHours": 4,
            "actualHours": 4,
            "location": "Office/Remote",
            "notes": "[At 10:00 AM] Logged from Daily Logs board",
            "subtasks": [],
            "comments": [],
            "createdAt": "2026-07-08",
            "tags": []
      },
      {
            "id": "TASK-037",
            "title": "Meeting with Dr. Haytham",
            "description": "",
            "status": "col-done",
            "priority": "medium",
            "assignee": "Sallam",
            "startDate": "2026-07-08",
            "dueDate": "2026-07-08",
            "estimatedHours": 4,
            "actualHours": 4,
            "location": "Office/Remote",
            "notes": "[At 10:00 AM] Logged from Daily Logs board",
            "subtasks": [],
            "comments": [],
            "createdAt": "2026-07-08",
            "tags": []
      },
      {
            "id": "TASK-038",
            "title": "Debugging Printer",
            "description": "",
            "status": "col-done",
            "priority": "medium",
            "assignee": "Sallam",
            "startDate": "2026-07-08",
            "dueDate": "2026-07-08",
            "estimatedHours": 4,
            "actualHours": 4,
            "location": "Office/Remote",
            "notes": "[At 10:00 AM] Logged from Daily Logs board",
            "subtasks": [],
            "comments": [],
            "createdAt": "2026-07-08",
            "tags": []
      },
      {
            "id": "TASK-039",
            "title": "Debgging Printer",
            "description": "",
            "status": "col-done",
            "priority": "medium",
            "assignee": "Sallam",
            "startDate": "2026-07-07",
            "dueDate": "2026-07-07",
            "estimatedHours": 4,
            "actualHours": 4,
            "location": "Office/Remote",
            "notes": "[At 10:00 AM] Logged from Daily Logs board",
            "subtasks": [],
            "comments": [],
            "createdAt": "2026-07-07",
            "tags": []
      },
      {
            "id": "TASK-040",
            "title": "Inventroy Assets Assistance",
            "description": "",
            "status": "col-done",
            "priority": "medium",
            "assignee": "Sallam",
            "startDate": "2026-07-07",
            "dueDate": "2026-07-07",
            "estimatedHours": 4,
            "actualHours": 4,
            "location": "Office/Remote",
            "notes": "[At 10:00 AM] Logged from Daily Logs board",
            "subtasks": [],
            "comments": [],
            "createdAt": "2026-07-07",
            "tags": []
      },
      {
            "id": "TASK-041",
            "title": "Mohannad Cubic 3D Printer",
            "description": "",
            "status": "col-done",
            "priority": "medium",
            "assignee": "Sallam",
            "startDate": "2026-07-06",
            "dueDate": "2026-07-06",
            "estimatedHours": 4,
            "actualHours": 4,
            "location": "Office/Remote",
            "notes": "[At 10:00 AM] Logged from Daily Logs board",
            "subtasks": [],
            "comments": [],
            "createdAt": "2026-07-06",
            "tags": []
      },
      {
            "id": "TASK-042",
            "title": "3D Printer Debugging Methodolgy",
            "description": "",
            "status": "col-todo",
            "priority": "medium",
            "assignee": "Unassigned",
            "startDate": "2026-07-09",
            "dueDate": "2026-07-09",
            "estimatedHours": 4,
            "actualHours": 4,
            "location": "Office/Remote",
            "notes": "[At 10:00 AM] Logged from Daily Logs board",
            "subtasks": [],
            "comments": [],
            "createdAt": "2026-07-09",
            "tags": []
      },
      {
            "id": "TASK-043",
            "title": "Dr Amr Safwat Presentation",
            "description": "",
            "status": "col-todo",
            "priority": "medium",
            "assignee": "Unassigned",
            "startDate": "2026-07-09",
            "dueDate": "2026-07-09",
            "estimatedHours": 4,
            "actualHours": 4,
            "location": "Office/Remote",
            "notes": "[At 10:00 AM] Logged from Daily Logs board",
            "subtasks": [],
            "comments": [],
            "createdAt": "2026-07-09",
            "tags": []
      },
      {
            "id": "TASK-044",
            "title": "SolidWorks Training",
            "description": "",
            "status": "col-todo",
            "priority": "medium",
            "assignee": "Unassigned",
            "startDate": "2026-07-09",
            "dueDate": "2026-07-09",
            "estimatedHours": 4,
            "actualHours": 4,
            "location": "Office/Remote",
            "notes": "[At 10:00 AM] Logged from Daily Logs board",
            "subtasks": [],
            "comments": [],
            "createdAt": "2026-07-09",
            "tags": []
      },
      {
            "id": "TASK-045",
            "title": "David Flapping Meeting",
            "description": "",
            "status": "col-todo",
            "priority": "medium",
            "assignee": "Unassigned",
            "startDate": "2026-07-09",
            "dueDate": "2026-07-09",
            "estimatedHours": 4,
            "actualHours": 4,
            "location": "Office/Remote",
            "notes": "[At 10:00 AM] Logged from Daily Logs board",
            "subtasks": [],
            "comments": [],
            "createdAt": "2026-07-09",
            "tags": []
      },
      {
            "id": "TASK-046",
            "title": "Agile Methodology",
            "description": "",
            "status": "col-todo",
            "priority": "medium",
            "assignee": "Unassigned",
            "startDate": "2026-07-12",
            "dueDate": "2026-07-12",
            "estimatedHours": 4,
            "actualHours": 4,
            "location": "Office/Remote",
            "notes": "[At 09:00 AM] Logged from Daily Logs board",
            "subtasks": [],
            "comments": [],
            "createdAt": "2026-07-12",
            "tags": []
      },
            {
        "id": "TASK-003",
        "title": "Innovation Hub Visualizer Kit",
        "description": "",
        "status": "col-done",
        "priority": "medium",
        "startDate": "2026-06-20",
        "dueDate": "2026-06-20",
        "assignee": "Abdallah",
        "tags": [],
        "estimatedHours": 5,
        "actualHours": 5,
        "location": "Office/Remote",
        "notes": "Logged from Daily Logs board",
        "subtasks": [],
        "comments": [],
        "createdAt": "2026-06-20"
      },
      {
        "id": "TASK-006",
        "title": "Test Run v0.2",
        "description": "",
        "status": "col-done",
        "priority": "urgent",
        "startDate": "2026-06-21",
        "dueDate": "2026-06-21",
        "assignee": "Abdallah",
        "tags": [],
        "estimatedHours": 1,
        "actualHours": 1,
        "location": "Office/Remote",
        "notes": "[At 02:00 AM] Stest run of the visualizer V0.2",
        "subtasks": [],
        "comments": [],
        "createdAt": "2026-06-21"
      },
      {
        "id": "TASK-007",
        "title": "ECE Measurement Test Out",
        "description": "",
        "status": "col-done",
        "priority": "medium",
        "startDate": "2026-06-21",
        "dueDate": "2026-06-21",
        "assignee": "Sallam",
        "tags": [],
        "estimatedHours": 8,
        "actualHours": 8,
        "location": "Office/Remote",
        "notes": "[At 09:00 AM] ECE Department Measurement Testout Sessions",
        "subtasks": [],
        "comments": [],
        "createdAt": "2026-06-21"
      },
      {
        "id": "TASK-008",
        "title": "Tasneem 3D Printing",
        "description": "",
        "status": "col-done",
        "priority": "medium",
        "startDate": "2026-06-22",
        "dueDate": "2026-06-22",
        "assignee": "Unassigned",
        "tags": [],
        "estimatedHours": 1,
        "actualHours": 4,
        "location": "Office/Remote",
        "notes": "[At 09:00 AM]\n-D:\\Abdallah Salaheldean\\Innovation\\3D-Printing\\Tasneem Tarek Abdelkereem\\21-6-2026\\New Print 2023\\200 mm\\0_Taber ratio",
        "subtasks": [],
        "comments": [],
        "createdAt": "2026-06-22"
      },
      {
        "id": "TASK-009",
        "title": "3D Printing Variable Layer Height",
        "description": "",
        "status": "col-done",
        "priority": "medium",
        "startDate": "2026-06-22",
        "dueDate": "2026-06-22",
        "assignee": "Unassigned",
        "tags": [],
        "estimatedHours": 1,
        "actualHours": 1,
        "location": "Office/Remote",
        "notes": "[At 09:00 AM] - https://www.youtube.com/shorts/jVD0irMC4L8\n- Find a Model to try it out - Done\n- https://www.youtube.com/watch?v=gTQg5fSs_as&t=39s",
        "subtasks": [],
        "comments": [],
        "createdAt": "2026-06-22"
      },
      {
        "id": "TASK-010",
        "title": "3D Printing Thermal Tower",
        "description": "",
        "status": "col-done",
        "priority": "medium",
        "startDate": "2026-06-22",
        "dueDate": "2026-06-22",
        "assignee": "Unassigned",
        "tags": [],
        "estimatedHours": 1,
        "actualHours": 1,
        "location": "Office/Remote",
        "notes": "[At 09:00 AM] - https://www.youtube.com/watch?v=WR2tRwzFlq0&t=83s\n-https://www.printables.com/model/20652-temp-tower-pla-petg-absasa-for-prusa-mini-mk3s-and",
        "subtasks": [],
        "comments": [],
        "createdAt": "2026-06-22"
      },
      {
        "id": "TASK-011",
        "title": "Masters",
        "description": "",
        "status": "col-done",
        "priority": "urgent",
        "startDate": "2026-06-20",
        "dueDate": "2026-06-23",
        "assignee": "Sallam",
        "tags": [],
        "estimatedHours": 10,
        "actualHours": 0,
        "location": "Remote",
        "notes": "[At 09:00 AM]",
        "subtasks": [],
        "comments": [],
        "createdAt": "2026-06-20"
      },
      {
        "id": "TASK-012",
        "title": "3DP G-Code",
        "description": "",
        "status": "col-done",
        "priority": "medium",
        "startDate": "2026-06-23",
        "dueDate": "2026-06-24",
        "assignee": "Abdallah",
        "tags": [],
        "estimatedHours": 4,
        "actualHours": 4,
        "location": "Office/Remote",
        "notes": "[At 09:00 AM] Eng. Shad - Check that the G Code matches the prusa\n\n# ROLE\nYou are a G-code verification assistant. Your job is to examine a G-code file and determine whether it is safe to print on my specific 3D printer. Be precise and conservative: when something is ambiguous or missing, say so rather than assuming.\n\n# MY PRINTER (the target)\n- Model: Prusa i3 MK3S+ (MK3S-compatible G-code is fine)\n- Nozzle: 0.4 mm\n- Build volume: 250 (X) × 210 (Y) × 210 (Z) mm\n- Firmware: Marlin (Prusa fork)\n- File format expected: plain-text .gcode (NOT binary .bgcode)\n\n# WHAT TO DO\nRead the file's header/config comments AND scan the actual motion commands. Do not rely only on the comment block — verify against the real G-code body. Then run every check below and report findings.\n\n# HARD RULES (a FAIL on any of these = \"DO NOT PRINT\")\n1. NOZZLE: Find nozzle_diameter. If it is not 0.4 mm, FAIL.\n2. BUILD VOLUME: Scan all X/Y/Z coordinates in the motion commands. If any X > 250, Y > 210, or Z > 210, the model won't fit — FAIL. Report the max X, Y, Z actually reached.\n3. FLAVOR: Confirm the G-code flavor is Marlin. If it is Klipper, RepRap/Duet, Bambu/X1-specific, or anything non-Marlin, FAIL.\n4. PRINTER MODEL: Look for printer_model / compatible printers / settings IDs.\n - If it names a Prusa MK3S/MK3S+, PASS this check.\n - If it names a DIFFERENT printer (MK4, MINI, Ender, Bambu, etc.), FAIL.\n5. FILE TYPE: If the content is binary/garbled rather than readable text commands, it may be .bgcode — FAIL and tell me to re-export as plain G-code.\n6. UNSUPPORTED COMMANDS: Flag any machine-specific codes the Prusa Marlin firmware would not understand — e.g. AMS/multi-material toolchanges, vendor-only M-codes (Bambu, Klipper macros). Note them. Core moves (G0/G1/G2/G3, G28, G29, M104/M109/M140/M190, M106) are all fine.\n\n# SAFETY CHECKS (a problem here = \"PRINT WITH CAUTION\", not an automatic fail)\n7. TEMPERATURES: Report nozzle and bed temps (M104/M109/M140/M190). Flag if nozzle > 300 °C or bed > 120 °C, or if temps look wrong for the stated filament (e.g. PLA above ~230 °C, or 0 °C where heat is expected).\n8. MODEL-CHECK LINE: Note whether an M862.3 model-check line is present.\n - Present and matching MK3S = good, the printer will self-verify.\n - ABSENT (common when sliced in non-Prusa slicers like Bambu Studio or Cura) = the printer will NOT verify the model itself, so I'm trusting the profile. Tell me this so I watch the first layer.\n9. START/END SEQUENCE: Confirm there's a sane startup (home G28, usually mesh leveling G29, a purge/intro line) and a sane ending (turn off heaters M104 S0 / M140 S0, fan off M107, park, disable motors M84). Flag if missing.\n10. BED ORIGIN / OFFSETS: Note if coordinates look shifted off the bed or use an unexpected origin that could cause the nozzle to crash or print off-plate.\n\n# SLICER NOTE\nIdentify which slicer and version produced the file (from the header). It's OK if it's not PrusaSlicer (e.g. Bambu Studio or Cura targeting a Prusa profile) — just confirm the profile/settings actually target the MK3S and the rules above pass.\n\n# OUTPUT FORMAT (use exactly this)\n**VERDICT:** ✅ SAFE TO PRINT / ⚠️ PRINT WITH CAUTION / ❌ DO NOT PRINT\n\n**Sliced by:** <slicer + version>\n**Target printer in file:** <printer_model found>\n**Nozzle:** <value>\n**Max dimensions reached:** X__ Y__ Z__ (vs limits 250×210×210)\n**Flavor:** <Marlin / other>\n**Temps:** nozzle __°C, bed __°C (filament: __)\n**M862.3 model check:** present / absent\n**Start/End sequence:** ok / issues\n\n**Why:** <2–4 sentence plain explanation of the verdict>\n**Watch out for:** <anything I should monitor, or \"nothing — looks clean\">",
        "subtasks": [],
        "comments": [],
        "createdAt": "2026-06-23"
      },
      {
        "id": "TASK-013",
        "title": "Robotino Day 2 Report",
        "description": "",
        "status": "col-done",
        "priority": "medium",
        "startDate": "2026-06-24",
        "dueDate": "2026-06-25",
        "assignee": "Unassigned",
        "tags": [],
        "estimatedHours": 1,
        "actualHours": 1,
        "location": "Office/Remote",
        "notes": "[At 09:00 AM] Write a report and a LinkedIn link here",
        "subtasks": [],
        "comments": [],
        "createdAt": "2026-06-24"
      },
      {
        "id": "TASK-014",
        "title": "Robotino Sessions",
        "description": "",
        "status": "col-done",
        "priority": "medium",
        "startDate": "2026-06-23",
        "dueDate": "2026-06-26",
        "assignee": "Unassigned",
        "tags": [],
        "estimatedHours": 32,
        "actualHours": 8,
        "location": "Office/Remote",
        "notes": "[At 09:00 AM] Logged from Daily Logs board",
        "subtasks": [],
        "comments": [],
        "createdAt": "2026-06-23"
      },
      {
        "id": "TASK-015",
        "title": "shahd printing files",
        "description": "",
        "status": "col-done",
        "priority": "medium",
        "startDate": "2026-06-24",
        "dueDate": "2026-06-24",
        "assignee": "Unassigned",
        "tags": [],
        "estimatedHours": 3,
        "actualHours": 3,
        "location": "Office/Remote",
        "notes": "[At 09:00 AM] together\nD:\\sallam\\shahad\\G-codes for printing\nD638 Type 1 _50_Cubic_PLA+_31m31s_7.94g.gcode",
        "subtasks": [],
        "comments": [],
        "createdAt": "2026-06-24"
      },
      {
        "id": "TASK-016",
        "title": "Tasneem 3D printing 200 mm",
        "description": "",
        "status": "col-done",
        "priority": "low",
        "startDate": "2026-06-24",
        "dueDate": "2026-06-25",
        "assignee": "Unassigned",
        "tags": [],
        "estimatedHours": 12,
        "actualHours": 12,
        "location": "Office/Remote",
        "notes": "[At 09:00 AM] D:\\Abdallah Salaheldean\\Innovation\\3D-Printing\\Tasneem Tarek Abdelkereem\\21-6-2026\\New Print 2023\\200 mm\\0.2_Taber ratio",
        "subtasks": [],
        "comments": [],
        "createdAt": "2026-06-24"
      },
      {
        "id": "TASK-017",
        "title": "Entity Survey : Eltoukhy Learning Factory",
        "description": "",
        "status": "col-done",
        "priority": "medium",
        "startDate": "2026-06-27",
        "dueDate": "2026-06-27",
        "assignee": "Abdallah",
        "tags": [],
        "estimatedHours": 4,
        "actualHours": 4,
        "location": "Office/Remote",
        "notes": "[At 10:00 AM] Logged from Daily Logs board",
        "subtasks": [],
        "comments": [],
        "createdAt": "2026-06-27"
      },
      {
        "id": "TASK-018",
        "title": "Entity Survey : Ain Shams University iHub",
        "description": "",
        "status": "col-done",
        "priority": "medium",
        "startDate": "2026-06-28",
        "dueDate": "2026-06-29",
        "assignee": "Abdallah",
        "tags": [],
        "estimatedHours": 4,
        "actualHours": 4,
        "location": "Office/Remote",
        "notes": "[At 09:00 AM] Logged from Daily Logs board",
        "subtasks": [],
        "comments": [],
        "createdAt": "2026-06-28"
      },
      {
        "id": "TASK-019",
        "title": "3D Printers Amr Safwat Report",
        "description": "",
        "status": "col-progress",
        "priority": "medium",
        "startDate": "2026-06-29",
        "dueDate": "2026-06-29",
        "assignee": "Sallam",
        "tags": [],
        "estimatedHours": 4,
        "actualHours": 4,
        "location": "Office/Remote",
        "notes": "[At 10:45 AM] Logged from Daily Logs board",
        "subtasks": [],
        "comments": [],
        "createdAt": "2026-06-29"
      },
      {
        "id": "TASK-020",
        "title": "3D Printing Shahd",
        "description": "",
        "status": "col-done",
        "priority": "medium",
        "startDate": "2026-06-29",
        "dueDate": "2026-06-29",
        "assignee": "Unassigned",
        "tags": [],
        "estimatedHours": 4,
        "actualHours": 4,
        "location": "Office/Remote",
        "notes": "[At 09:00 AM] D:\\Abdallah Salaheldean\\Innovation\\3D-Printing\\Shahd\\25-06-2026\\1_D638 Type 1 _50_Grid_PLA+_32m14s_7.93g",
        "subtasks": [],
        "comments": [],
        "createdAt": "2026-06-29"
      },
      {
        "id": "TASK-021",
        "title": "3D Printing Egals",
        "description": "",
        "status": "col-done",
        "priority": "medium",
        "startDate": "2026-06-29",
        "dueDate": "2026-06-29",
        "assignee": "Unassigned",
        "tags": [],
        "estimatedHours": 4,
        "actualHours": 4,
        "location": "Office/Remote",
        "notes": "[At 09:00 AM] D:\\Abdallah Salaheldean\\Innovation\\3D-Printing\\Eagles\\28-06-2026\\air cover 1 p1",
        "subtasks": [],
        "comments": [],
        "createdAt": "2026-06-29"
      },
      {
        "id": "TASK-022",
        "title": "Civil Shaker Request and Foam Cutting",
        "description": "",
        "status": "col-done",
        "priority": "medium",
        "startDate": "2026-06-29",
        "dueDate": "2026-06-29",
        "assignee": "Unassigned",
        "tags": [],
        "estimatedHours": 1,
        "actualHours": 1,
        "location": "Office/Remote",
        "notes": "[At 04:00 PM] Logged from Daily Logs board",
        "subtasks": [],
        "comments": [],
        "createdAt": "2026-06-29"
      },
      {
        "id": "TASK-023",
        "title": "Mohannad 3D Printing",
        "description": "",
        "status": "col-progress",
        "priority": "medium",
        "startDate": "2026-06-30",
        "dueDate": "2026-06-30",
        "assignee": "Unassigned",
        "tags": [],
        "estimatedHours": 4,
        "actualHours": 4,
        "location": "Office/Remote",
        "notes": "[At 10:00 AM] Logged from Daily Logs board",
        "subtasks": [],
        "comments": [],
        "createdAt": "2026-06-30"
      },
      {
        "id": "TASK-024",
        "title": "Shahd 3D Printing",
        "description": "",
        "status": "col-done",
        "priority": "medium",
        "startDate": "2026-06-30",
        "dueDate": "2026-06-30",
        "assignee": "Unassigned",
        "tags": [],
        "estimatedHours": 4,
        "actualHours": 4,
        "location": "Office/Remote",
        "notes": "[At 09:00 AM] D:\\Abdallah Salaheldean\\Innovation\\3D-Printing\\Shahd\\25-06-2026\\2_D638 Type 1 _50_Honeycomb_PLA+_51m11s_8.43g.gcode",
        "subtasks": [],
        "comments": [],
        "createdAt": "2026-06-30"
      },
      {
        "id": "TASK-025",
        "title": "Eman/David Thermal Device",
        "description": "",
        "status": "col-blocked",
        "priority": "medium",
        "startDate": "2026-06-30",
        "dueDate": "2026-06-30",
        "assignee": "Sallam",
        "tags": [],
        "estimatedHours": 4,
        "actualHours": 4,
        "location": "Office/Remote",
        "notes": "[At 10:00 AM] Logged from Daily Logs board",
        "subtasks": [],
        "comments": [],
        "createdAt": "2026-06-30"
      },
      {
        "id": "TASK-026",
        "title": "ESP-Cam 3D Printer and Tools Monitoring",
        "description": "",
        "status": "col-todo",
        "priority": "medium",
        "startDate": "2026-06-30",
        "dueDate": "2026-06-30",
        "assignee": "Abdallah",
        "tags": [],
        "estimatedHours": 4,
        "actualHours": 4,
        "location": "Office/Remote",
        "notes": "[At 09:00 AM] Logged from Daily Logs board",
        "subtasks": [],
        "comments": [],
        "createdAt": "2026-06-30"
      },
      {
        "id": "TASK-027",
        "title": "Electronic Workbench",
        "description": "",
        "status": "col-progress",
        "priority": "medium",
        "startDate": "2026-06-30",
        "dueDate": "2026-06-30",
        "assignee": "Abdallah",
        "tags": [],
        "estimatedHours": 4,
        "actualHours": 4,
        "location": "Office/Remote",
        "notes": "[At 09:00 AM] Logged from Daily Logs board",
        "subtasks": [],
        "comments": [],
        "createdAt": "2026-06-30"
      },
      {
        "id": "TASK-028",
        "title": "Ahmed Ibrahim",
        "description": "",
        "status": "col-blocked",
        "priority": "medium",
        "startDate": "2026-06-30",
        "dueDate": "2026-06-30",
        "assignee": "Unassigned",
        "tags": [],
        "estimatedHours": 4,
        "actualHours": 4,
        "location": "Office/Remote",
        "notes": "[At 10:00 AM] Logged from Daily Logs board",
        "subtasks": [],
        "comments": [],
        "createdAt": "2026-06-30"
      },
      {
        "id": "TASK-029",
        "title": "Claude Code Vercel Visualizer Web-Kit",
        "description": "",
        "status": "col-todo",
        "priority": "medium",
        "startDate": "2026-06-20",
        "dueDate": "2026-06-20",
        "assignee": "Abdallah",
        "tags": [],
        "estimatedHours": 10,
        "actualHours": 0,
        "location": "Remote",
        "notes": "[At 09:00 AM]",
        "subtasks": [],
        "comments": [],
        "createdAt": "2026-06-20"
      },
      {
        "id": "TASK-030",
        "title": "Eagles Printing",
        "description": "",
        "status": "col-progress",
        "priority": "medium",
        "startDate": "2026-07-06",
        "dueDate": "2026-07-06",
        "assignee": "Unassigned",
        "tags": [],
        "estimatedHours": 3,
        "actualHours": 3,
        "location": "Office/Remote",
        "notes": "[At 11:00 AM] Logged from Daily Logs board",
        "subtasks": [],
        "comments": [],
        "createdAt": "2026-07-06"
      },
      {
        "id": "TASK-031",
        "title": "HPDE Manfacting With Civil Eng. Mohammed Mohsen",
        "description": "",
        "status": "col-progress",
        "priority": "medium",
        "startDate": "2026-07-06",
        "dueDate": "2026-07-06",
        "assignee": "Unassigned",
        "tags": [],
        "estimatedHours": 4,
        "actualHours": 4,
        "location": "Office/Remote",
        "notes": "[At 01:00 PM] Logged from Daily Logs board",
        "subtasks": [],
        "comments": [],
        "createdAt": "2026-07-06"
      },
      {
        "id": "TASK-032",
        "title": "Prusa Thermal Modle Error",
        "description": "",
        "status": "col-progress",
        "priority": "medium",
        "startDate": "2026-07-06",
        "dueDate": "2026-07-06",
        "assignee": "Abdallah",
        "tags": [],
        "estimatedHours": 4,
        "actualHours": 4,
        "location": "Office/Remote",
        "notes": "[At 10:00 AM] Logged from Daily Logs board",
        "subtasks": [],
        "comments": [],
        "createdAt": "2026-07-06"
      }
    ]
  },
{
  "id": "proj-innovation-hub-sync",
  "name": "Sync Data - Innovation Hub",
  "description": "Tasks synced from CSV.",
  "tags": [],
  "modules": [],
  "goals": [],
  "parentId": "proj-innovation-hub",
  "color": "#3b82f6",
  "icon": "📊",
  "columns": [
    {
      "id": "col-todo",
      "title": "To Do",
      "color": "#64748b"
    },
    {
      "id": "col-progress",
      "title": "In Progress",
      "color": "#3b82f6"
    },
    {
      "id": "col-blocked",
      "title": "Blocked",
      "color": "#f43f5e"
    },
    {
      "id": "col-done",
      "title": "Completed",
      "color": "#10b981"
    }
  ],
  "tasks": [
    {
      "id": "TASK-003",
      "title": "Innovation Hub Visualizer Kit",
      "description": "",
      "status": "col-done",
      "priority": "medium",
      "assignee": "Abdallah",
      "startDate": "2026-06-19",
      "dueDate": "2026-06-19",
      "estimatedHours": 5,
      "actualHours": 5,
      "location": "Office/Remote",
      "notes": "Logged from Daily Logs board",
      "subtasks": [],
      "comments": [],
      "createdAt": "2026-06-19",
      "tags": []
    },
    {
      "id": "TASK-006",
      "title": "Test Run v0.2",
      "description": "",
      "status": "col-done",
      "priority": "urgent",
      "assignee": "Abdallah",
      "startDate": "2026-06-20",
      "dueDate": "2026-06-20",
      "estimatedHours": 1,
      "actualHours": 1,
      "location": "Office/Remote",
      "notes": "[At 02:00 AM] Stest run of the visualizer V0.2",
      "subtasks": [],
      "comments": [],
      "createdAt": "2026-06-20",
      "tags": []
    },
    {
      "id": "TASK-007",
      "title": "ECE Measurement Test Out",
      "description": "",
      "status": "col-done",
      "priority": "medium",
      "assignee": "Sallam",
      "startDate": "2026-06-20",
      "dueDate": "2026-06-20",
      "estimatedHours": 8,
      "actualHours": 8,
      "location": "Office/Remote",
      "notes": "[At 09:00 AM] ECE Department Measurement Testout Sessions",
      "subtasks": [],
      "comments": [],
      "createdAt": "2026-06-20",
      "tags": []
    },
    {
      "id": "TASK-008",
      "title": "Tasneem 3D Printing",
      "description": "",
      "status": "col-done",
      "priority": "medium",
      "assignee": "Unassigned",
      "startDate": "2026-06-21",
      "dueDate": "2026-06-21",
      "estimatedHours": 1,
      "actualHours": 4,
      "location": "Office/Remote",
      "notes": "[At 09:00 AM] \n-D:\\Abdallah Salaheldean\\Innovation\\3D-Printing\\Tasneem Tarek Abdelkereem\\21-6-2026\\New Print 2023\\200 mm\\0_Taber ratio",
      "subtasks": [],
      "comments": [],
      "createdAt": "2026-06-21",
      "tags": []
    },
    {
      "id": "TASK-009",
      "title": "3D Printing Variable Layer Height",
      "description": "",
      "status": "col-done",
      "priority": "medium",
      "assignee": "Unassigned",
      "startDate": "2026-06-21",
      "dueDate": "2026-06-21",
      "estimatedHours": 1,
      "actualHours": 1,
      "location": "Office/Remote",
      "notes": "[At 09:00 AM] - https://www.youtube.com/shorts/jVD0irMC4L8\n\n- Find a Model to try it out - Done\n\n- https://www.youtube.com/watch?v=gTQg5fSs_as&t=39s",
      "subtasks": [],
      "comments": [],
      "createdAt": "2026-06-21",
      "tags": []
    },
    {
      "id": "TASK-010",
      "title": "3D Printing Thermal Tower",
      "description": "",
      "status": "col-done",
      "priority": "medium",
      "assignee": "Unassigned",
      "startDate": "2026-06-21",
      "dueDate": "2026-06-21",
      "estimatedHours": 1,
      "actualHours": 1,
      "location": "Office/Remote",
      "notes": "[At 09:00 AM] - https://www.youtube.com/watch?v=WR2tRwzFlq0&t=83s\n-https://www.printables.com/model/20652-temp-tower-pla-petg-absasa-for-prusa-mini-mk3s-and",
      "subtasks": [],
      "comments": [],
      "createdAt": "2026-06-21",
      "tags": []
    },
    {
      "id": "TASK-011",
      "title": "Masters",
      "description": "",
      "status": "col-done",
      "priority": "urgent",
      "assignee": "Sallam",
      "startDate": "2026-06-19",
      "dueDate": "2026-06-22",
      "estimatedHours": 10,
      "actualHours": 0,
      "location": "Remote",
      "notes": "[At 09:00 AM] ",
      "subtasks": [],
      "comments": [],
      "createdAt": "2026-06-19",
      "tags": []
    },
    {
      "id": "TASK-012",
      "title": "3DP G-Code",
      "description": "",
      "status": "col-done",
      "priority": "medium",
      "assignee": "Abdallah",
      "startDate": "2026-06-22",
      "dueDate": "2026-06-23",
      "estimatedHours": 4,
      "actualHours": 4,
      "location": "Office/Remote",
      "notes": "[At 09:00 AM] Eng. Shad - Check that the G Code matches the prusa\n\n# ROLE\nYou are a G-code verification assistant. Your job is to examine a G-code file and\ndetermine whether it is safe to print on my specific 3D printer. Be precise and\nconservative: when something is ambiguous or missing, say so rather than assuming.\n\n# MY PRINTER (the target)\n- Model: Prusa i3 MK3S+ (MK3S-compatible G-code is fine)\n- Nozzle: 0.4 mm\n- Build volume: 250 (X) × 210 (Y) × 210 (Z) mm\n- Firmware: Marlin (Prusa fork)\n- File format expected: plain-text .gcode (NOT binary .bgcode)\n\n# WHAT TO DO\nRead the file's header/config comments AND scan the actual motion commands.\nDo not rely only on the comment block — verify against the real G-code body.\nThen run every check below and report findings.\n\n# HARD RULES (a FAIL on any of these = \"DO NOT PRINT\")\n1. NOZZLE: Find nozzle_diameter. If it is not 0.4 mm, FAIL.\n2. BUILD VOLUME: Scan all X/Y/Z coordinates in the motion commands. If any\n   X > 250, Y > 210, or Z > 210, the model won't fit — FAIL. Report the max\n   X, Y, Z actually reached.\n3. FLAVOR: Confirm the G-code flavor is Marlin. If it is Klipper, RepRap/Duet,\n   Bambu/X1-specific, or anything non-Marlin, FAIL.\n4. PRINTER MODEL: Look for printer_model / compatible printers / settings IDs.\n   - If it names a Prusa MK3S/MK3S+, PASS this check.\n   - If it names a DIFFERENT printer (MK4, MINI, Ender, Bambu, etc.), FAIL.\n5. FILE TYPE: If the content is binary/garbled rather than readable text\n   commands, it may be .bgcode — FAIL and tell me to re-export as plain G-code.\n6. UNSUPPORTED COMMANDS: Flag any machine-specific codes the Prusa Marlin\n   firmware would not understand — e.g. AMS/multi-material toolchanges, vendor-\n   only M-codes (Bambu, Klipper macros). Note them. Core moves (G0/G1/G2/G3,\n   G28, G29, M104/M109/M140/M190, M106) are all fine.\n\n# SAFETY CHECKS (a problem here = \"PRINT WITH CAUTION\", not an automatic fail)\n7. TEMPERATURES: Report nozzle and bed temps (M104/M109/M140/M190). Flag if\n   nozzle > 300 °C or bed > 120 °C, or if temps look wrong for the stated\n   filament (e.g. PLA above ~230 °C, or 0 °C where heat is expected).\n8. MODEL-CHECK LINE: Note whether an M862.3 model-check line is present.\n   - Present and matching MK3S = good, the printer will self-verify.\n   - ABSENT (common when sliced in non-Prusa slicers like Bambu Studio or Cura)\n     = the printer will NOT verify the model itself, so I'm trusting the profile.\n     Tell me this so I watch the first layer.\n9. START/END SEQUENCE: Confirm there's a sane startup (home G28, usually mesh\n   leveling G29, a purge/intro line) and a sane ending (turn off heaters M104 S0\n   / M140 S0, fan off M107, park, disable motors M84). Flag if missing.\n10. BED ORIGIN / OFFSETS: Note if coordinates look shifted off the bed or use an\n    unexpected origin that could cause the nozzle to crash or print off-plate.\n\n# SLICER NOTE\nIdentify which slicer and version produced the file (from the header). It's OK\nif it's not PrusaSlicer (e.g. Bambu Studio or Cura targeting a Prusa profile) —\njust confirm the profile/settings actually target the MK3S and the rules above pass.\n\n# OUTPUT FORMAT (use exactly this)\n**VERDICT:** ✅ SAFE TO PRINT  /  ⚠️ PRINT WITH CAUTION  /  ❌ DO NOT PRINT\n\n**Sliced by:** <slicer + version>\n**Target printer in file:** <printer_model found>\n**Nozzle:** <value>\n**Max dimensions reached:** X__ Y__ Z__ (vs limits 250×210×210)\n**Flavor:** <Marlin / other>\n**Temps:** nozzle __°C, bed __°C  (filament: __)\n**M862.3 model check:** present / absent\n**Start/End sequence:** ok / issues\n\n**Why:** <2–4 sentence plain explanation of the verdict>\n**Watch out for:** <anything I should monitor, or \"nothing — looks clean\">",
      "subtasks": [],
      "comments": [],
      "createdAt": "2026-06-22",
      "tags": []
    },
    {
      "id": "TASK-013",
      "title": "Robotino Day 2 Report",
      "description": "",
      "status": "col-done",
      "priority": "medium",
      "assignee": "Unassigned",
      "startDate": "2026-06-23",
      "dueDate": "2026-06-24",
      "estimatedHours": 1,
      "actualHours": 1,
      "location": "Office/Remote",
      "notes": "[At 09:00 AM] Write a report and a LinkedIn link here",
      "subtasks": [],
      "comments": [],
      "createdAt": "2026-06-23",
      "tags": []
    },
    {
      "id": "TASK-014",
      "title": "Robotino Sessions",
      "description": "",
      "status": "col-done",
      "priority": "medium",
      "assignee": "Unassigned",
      "startDate": "2026-06-22",
      "dueDate": "2026-06-25",
      "estimatedHours": 32,
      "actualHours": 8,
      "location": "Office/Remote",
      "notes": "[At 09:00 AM] Logged from Daily Logs board",
      "subtasks": [],
      "comments": [],
      "createdAt": "2026-06-22",
      "tags": []
    },
    {
      "id": "TASK-015",
      "title": "shahd printing  files",
      "description": "",
      "status": "col-done",
      "priority": "medium",
      "assignee": "Unassigned",
      "startDate": "2026-06-23",
      "dueDate": "2026-06-23",
      "estimatedHours": 3,
      "actualHours": 3,
      "location": "Office/Remote",
      "notes": "[At 09:00 AM] together\n\nD:\\sallam\\shahad\\G-codes for printing\nD638 Type 1 _50_Cubic_PLA+_31m31s_7.94g.gcode",
      "subtasks": [],
      "comments": [],
      "createdAt": "2026-06-23",
      "tags": []
    },
    {
      "id": "TASK-016",
      "title": "Tasneem 3D printing 200 mm",
      "description": "",
      "status": "col-done",
      "priority": "low",
      "assignee": "Unassigned",
      "startDate": "2026-06-23",
      "dueDate": "2026-06-24",
      "estimatedHours": 12,
      "actualHours": 12,
      "location": "Office/Remote",
      "notes": "[At 09:00 AM] D:\\Abdallah Salaheldean\\Innovation\\3D-Printing\\Tasneem Tarek Abdelkereem\\21-6-2026\\New Print 2023\\200 mm\\0.2_Taber ratio",
      "subtasks": [],
      "comments": [],
      "createdAt": "2026-06-23",
      "tags": []
    },
    {
      "id": "TASK-017",
      "title": "Entity Survey : Eltoukhy Learning Factory",
      "description": "",
      "status": "col-done",
      "priority": "medium",
      "assignee": "Abdallah",
      "startDate": "2026-06-26",
      "dueDate": "2026-06-26",
      "estimatedHours": 4,
      "actualHours": 4,
      "location": "Office/Remote",
      "notes": "[At 10:00 AM] Logged from Daily Logs board",
      "subtasks": [],
      "comments": [],
      "createdAt": "2026-06-26",
      "tags": []
    },
    {
      "id": "TASK-018",
      "title": "Entity Survey : Ain Shams University iHub",
      "description": "",
      "status": "col-done",
      "priority": "medium",
      "assignee": "Abdallah",
      "startDate": "2026-06-27",
      "dueDate": "2026-06-28",
      "estimatedHours": 4,
      "actualHours": 4,
      "location": "Office/Remote",
      "notes": "[At 09:00 AM] Logged from Daily Logs board",
      "subtasks": [],
      "comments": [],
      "createdAt": "2026-06-27",
      "tags": []
    },
    {
      "id": "TASK-019",
      "title": "3D Printers Amr Safwat Report",
      "description": "",
      "status": "col-progress",
      "priority": "medium",
      "assignee": "Sallam",
      "startDate": "2026-06-28",
      "dueDate": "2026-06-28",
      "estimatedHours": 4,
      "actualHours": 4,
      "location": "Office/Remote",
      "notes": "[At 10:45 AM] Logged from Daily Logs board",
      "subtasks": [],
      "comments": [],
      "createdAt": "2026-06-28",
      "tags": []
    },
    {
      "id": "TASK-020",
      "title": "3D Printing Shahd",
      "description": "",
      "status": "col-done",
      "priority": "medium",
      "assignee": "Unassigned",
      "startDate": "2026-06-28",
      "dueDate": "2026-06-28",
      "estimatedHours": 4,
      "actualHours": 4,
      "location": "Office/Remote",
      "notes": "[At 09:00 AM] D:\\Abdallah Salaheldean\\Innovation\\3D-Printing\\Shahd\\25-06-2026\\1_D638 Type 1 _50_Grid_PLA+_32m14s_7.93g",
      "subtasks": [],
      "comments": [],
      "createdAt": "2026-06-28",
      "tags": []
    },
    {
      "id": "TASK-021",
      "title": "3D Printing Egals",
      "description": "",
      "status": "col-done",
      "priority": "medium",
      "assignee": "Unassigned",
      "startDate": "2026-06-28",
      "dueDate": "2026-06-28",
      "estimatedHours": 4,
      "actualHours": 4,
      "location": "Office/Remote",
      "notes": "[At 09:00 AM] D:\\Abdallah Salaheldean\\Innovation\\3D-Printing\\Eagles\\28-06-2026\\air cover 1 p1",
      "subtasks": [],
      "comments": [],
      "createdAt": "2026-06-28",
      "tags": []
    },
    {
      "id": "TASK-022",
      "title": "Civil Shaker Request and Foam Cutting",
      "description": "",
      "status": "col-done",
      "priority": "medium",
      "assignee": "Unassigned",
      "startDate": "2026-06-28",
      "dueDate": "2026-06-28",
      "estimatedHours": 1,
      "actualHours": 1,
      "location": "Office/Remote",
      "notes": "[At 04:00 PM] Logged from Daily Logs board",
      "subtasks": [],
      "comments": [],
      "createdAt": "2026-06-28",
      "tags": []
    },
    {
      "id": "TASK-023",
      "title": "Mohannad 3D Printing",
      "description": "",
      "status": "col-progress",
      "priority": "medium",
      "assignee": "Unassigned",
      "startDate": "2026-06-29",
      "dueDate": "2026-06-29",
      "estimatedHours": 4,
      "actualHours": 4,
      "location": "Office/Remote",
      "notes": "[At 10:00 AM] Logged from Daily Logs board",
      "subtasks": [],
      "comments": [],
      "createdAt": "2026-06-29",
      "tags": []
    },
    {
      "id": "TASK-024",
      "title": "Shahd 3D Printing",
      "description": "",
      "status": "col-done",
      "priority": "medium",
      "assignee": "Unassigned",
      "startDate": "2026-06-29",
      "dueDate": "2026-06-29",
      "estimatedHours": 4,
      "actualHours": 4,
      "location": "Office/Remote",
      "notes": "[At 09:00 AM] D:\\Abdallah Salaheldean\\Innovation\\3D-Printing\\Shahd\\25-06-2026\\2_D638 Type 1 _50_Honeycomb_PLA+_51m11s_8.43g.gcode",
      "subtasks": [],
      "comments": [],
      "createdAt": "2026-06-29",
      "tags": []
    },
    {
      "id": "TASK-025",
      "title": "Eman/David Thermal Device",
      "description": "",
      "status": "col-blocked",
      "priority": "medium",
      "assignee": "Sallam",
      "startDate": "2026-06-29",
      "dueDate": "2026-06-29",
      "estimatedHours": 4,
      "actualHours": 4,
      "location": "Office/Remote",
      "notes": "[At 10:00 AM] Logged from Daily Logs board",
      "subtasks": [],
      "comments": [],
      "createdAt": "2026-06-29",
      "tags": []
    },
    {
      "id": "TASK-026",
      "title": "ESP-Cam 3D Printer and Tools Monitoring",
      "description": "",
      "status": "col-todo",
      "priority": "medium",
      "assignee": "Abdallah",
      "startDate": "2026-06-29",
      "dueDate": "2026-06-29",
      "estimatedHours": 4,
      "actualHours": 4,
      "location": "Office/Remote",
      "notes": "[At 09:00 AM] Logged from Daily Logs board",
      "subtasks": [],
      "comments": [],
      "createdAt": "2026-06-29",
      "tags": []
    },
    {
      "id": "TASK-027",
      "title": "Electronic Workbench",
      "description": "",
      "status": "col-progress",
      "priority": "medium",
      "assignee": "Abdallah",
      "startDate": "2026-06-29",
      "dueDate": "2026-06-29",
      "estimatedHours": 4,
      "actualHours": 4,
      "location": "Office/Remote",
      "notes": "[At 09:00 AM] Logged from Daily Logs board",
      "subtasks": [],
      "comments": [],
      "createdAt": "2026-06-29",
      "tags": []
    },
    {
      "id": "TASK-028",
      "title": "Ahmed Ibrahim تصفية العهدة",
      "description": "",
      "status": "col-blocked",
      "priority": "medium",
      "assignee": "Unassigned",
      "startDate": "2026-06-29",
      "dueDate": "2026-06-29",
      "estimatedHours": 4,
      "actualHours": 4,
      "location": "Office/Remote",
      "notes": "[At 10:00 AM] Logged from Daily Logs board",
      "subtasks": [],
      "comments": [],
      "createdAt": "2026-06-29",
      "tags": []
    },
    {
      "id": "TASK-029",
      "title": "Claude Code Vercel Visualizer Web-Kit",
      "description": "",
      "status": "col-progress",
      "priority": "medium",
      "assignee": "Abdallah",
      "startDate": "2026-06-19",
      "dueDate": "2026-06-19",
      "estimatedHours": 10,
      "actualHours": 0,
      "location": "Remote",
      "notes": "[At 09:00 AM] ",
      "subtasks": [],
      "comments": [],
      "createdAt": "2026-06-19",
      "tags": []
    },
    {
      "id": "TASK-030",
      "title": "Eagles Printing",
      "description": "",
      "status": "col-done",
      "priority": "medium",
      "assignee": "Unassigned",
      "startDate": "2026-07-05",
      "dueDate": "2026-07-05",
      "estimatedHours": 3,
      "actualHours": 3,
      "location": "Office/Remote",
      "notes": "[At 09:00 AM] Logged from Daily Logs board",
      "subtasks": [],
      "comments": [],
      "createdAt": "2026-07-05",
      "tags": []
    },
    {
      "id": "TASK-031",
      "title": "HPDE Manfacting With Civil Eng. Mohammed Mohsen",
      "description": "",
      "status": "col-progress",
      "priority": "medium",
      "assignee": "Unassigned",
      "startDate": "2026-07-05",
      "dueDate": "2026-07-05",
      "estimatedHours": 4,
      "actualHours": 4,
      "location": "Office/Remote",
      "notes": "[At 01:00 PM] Logged from Daily Logs board",
      "subtasks": [],
      "comments": [],
      "createdAt": "2026-07-05",
      "tags": []
    },
    {
      "id": "TASK-032",
      "title": "Prusa Thermal Modle Error",
      "description": "",
      "status": "col-done",
      "priority": "medium",
      "assignee": "Abdallah",
      "startDate": "2026-07-05",
      "dueDate": "2026-07-05",
      "estimatedHours": 4,
      "actualHours": 4,
      "location": "Office/Remote",
      "notes": "[At 09:00 AM] Logged from Daily Logs board",
      "subtasks": [],
      "comments": [],
      "createdAt": "2026-07-05",
      "tags": []
    },
    {
      "id": "TASK-033",
      "title": "Summer Workshop (PCB)",
      "description": "",
      "status": "col-todo",
      "priority": "medium",
      "assignee": "Unassigned",
      "startDate": "2026-07-27",
      "dueDate": "2026-07-27",
      "estimatedHours": 4,
      "actualHours": 4,
      "location": "Office/Remote",
      "notes": "[At 10:00 AM] Logged from Daily Logs board",
      "subtasks": [],
      "comments": [],
      "createdAt": "2026-07-27",
      "tags": []
    },
    {
      "id": "TASK-034",
      "title": "Orentation session (For Innovaton Hub) and Quizz",
      "description": "",
      "status": "col-todo",
      "priority": "medium",
      "assignee": "Unassigned",
      "startDate": "2026-08-04",
      "dueDate": "2026-08-04",
      "estimatedHours": 4,
      "actualHours": 4,
      "location": "Office/Remote",
      "notes": "[At 10:00 AM] Logged from Daily Logs board",
      "subtasks": [],
      "comments": [],
      "createdAt": "2026-08-04",
      "tags": []
    },
    {
      "id": "TASK-035",
      "title": "System for story when the student enter the innovation till he leaves",
      "description": "",
      "status": "col-todo",
      "priority": "medium",
      "assignee": "Unassigned",
      "startDate": "2026-08-04",
      "dueDate": "2026-08-04",
      "estimatedHours": 4,
      "actualHours": 4,
      "location": "Office/Remote",
      "notes": "[At 10:00 AM] Logged from Daily Logs board",
      "subtasks": [],
      "comments": [],
      "createdAt": "2026-08-04",
      "tags": []
    },
    {
      "id": "TASK-036",
      "title": "Reply for laser cutting email",
      "description": "",
      "status": "col-progress",
      "priority": "medium",
      "assignee": "Sallam",
      "startDate": "2026-07-08",
      "dueDate": "2026-07-08",
      "estimatedHours": 4,
      "actualHours": 4,
      "location": "Office/Remote",
      "notes": "[At 10:00 AM] Logged from Daily Logs board",
      "subtasks": [],
      "comments": [],
      "createdAt": "2026-07-08",
      "tags": []
    },
    {
      "id": "TASK-037",
      "title": "Meeting with Dr. Haytham",
      "description": "",
      "status": "col-done",
      "priority": "medium",
      "assignee": "Sallam",
      "startDate": "2026-07-08",
      "dueDate": "2026-07-08",
      "estimatedHours": 4,
      "actualHours": 4,
      "location": "Office/Remote",
      "notes": "[At 10:00 AM] Logged from Daily Logs board",
      "subtasks": [],
      "comments": [],
      "createdAt": "2026-07-08",
      "tags": []
    },
    {
      "id": "TASK-038",
      "title": "Debugging Printer",
      "description": "",
      "status": "col-done",
      "priority": "medium",
      "assignee": "Sallam",
      "startDate": "2026-07-08",
      "dueDate": "2026-07-08",
      "estimatedHours": 4,
      "actualHours": 4,
      "location": "Office/Remote",
      "notes": "[At 10:00 AM] Logged from Daily Logs board",
      "subtasks": [],
      "comments": [],
      "createdAt": "2026-07-08",
      "tags": []
    },
    {
      "id": "TASK-039",
      "title": "Debgging Printer",
      "description": "",
      "status": "col-done",
      "priority": "medium",
      "assignee": "Sallam",
      "startDate": "2026-07-07",
      "dueDate": "2026-07-07",
      "estimatedHours": 4,
      "actualHours": 4,
      "location": "Office/Remote",
      "notes": "[At 10:00 AM] Logged from Daily Logs board",
      "subtasks": [],
      "comments": [],
      "createdAt": "2026-07-07",
      "tags": []
    },
    {
      "id": "TASK-040",
      "title": "Inventroy Assets Assistance",
      "description": "",
      "status": "col-done",
      "priority": "medium",
      "assignee": "Sallam",
      "startDate": "2026-07-07",
      "dueDate": "2026-07-07",
      "estimatedHours": 4,
      "actualHours": 4,
      "location": "Office/Remote",
      "notes": "[At 10:00 AM] Logged from Daily Logs board",
      "subtasks": [],
      "comments": [],
      "createdAt": "2026-07-07",
      "tags": []
    },
    {
      "id": "TASK-041",
      "title": "Mohannad Cubic 3D Printer",
      "description": "",
      "status": "col-done",
      "priority": "medium",
      "assignee": "Sallam",
      "startDate": "2026-07-06",
      "dueDate": "2026-07-06",
      "estimatedHours": 4,
      "actualHours": 4,
      "location": "Office/Remote",
      "notes": "[At 10:00 AM] Logged from Daily Logs board",
      "subtasks": [],
      "comments": [],
      "createdAt": "2026-07-06",
      "tags": []
    },
    {
      "id": "TASK-042",
      "title": "3D Printer Debugging Methodolgy",
      "description": "",
      "status": "col-todo",
      "priority": "medium",
      "assignee": "Unassigned",
      "startDate": "2026-07-09",
      "dueDate": "2026-07-09",
      "estimatedHours": 4,
      "actualHours": 4,
      "location": "Office/Remote",
      "notes": "[At 10:00 AM] Logged from Daily Logs board",
      "subtasks": [],
      "comments": [],
      "createdAt": "2026-07-09",
      "tags": []
    },
    {
      "id": "TASK-043",
      "title": "Dr Amr Safwat Presentation",
      "description": "",
      "status": "col-todo",
      "priority": "medium",
      "assignee": "Unassigned",
      "startDate": "2026-07-09",
      "dueDate": "2026-07-09",
      "estimatedHours": 4,
      "actualHours": 4,
      "location": "Office/Remote",
      "notes": "[At 10:00 AM] Logged from Daily Logs board",
      "subtasks": [],
      "comments": [],
      "createdAt": "2026-07-09",
      "tags": []
    },
    {
      "id": "TASK-044",
      "title": "SolidWorks Training",
      "description": "",
      "status": "col-todo",
      "priority": "medium",
      "assignee": "Unassigned",
      "startDate": "2026-07-09",
      "dueDate": "2026-07-09",
      "estimatedHours": 4,
      "actualHours": 4,
      "location": "Office/Remote",
      "notes": "[At 10:00 AM] Logged from Daily Logs board",
      "subtasks": [],
      "comments": [],
      "createdAt": "2026-07-09",
      "tags": []
    },
    {
      "id": "TASK-045",
      "title": "David Flapping Meeting",
      "description": "",
      "status": "col-todo",
      "priority": "medium",
      "assignee": "Unassigned",
      "startDate": "2026-07-09",
      "dueDate": "2026-07-09",
      "estimatedHours": 4,
      "actualHours": 4,
      "location": "Office/Remote",
      "notes": "[At 10:00 AM] Logged from Daily Logs board",
      "subtasks": [],
      "comments": [],
      "createdAt": "2026-07-09",
      "tags": []
    },
    {
      "id": "TASK-046",
      "title": "Agile Methodology",
      "description": "",
      "status": "col-todo",
      "priority": "medium",
      "assignee": "Unassigned",
      "startDate": "2026-07-12",
      "dueDate": "2026-07-12",
      "estimatedHours": 4,
      "actualHours": 4,
      "location": "Office/Remote",
      "notes": "[At 09:00 AM] Logged from Daily Logs board",
      "subtasks": [],
      "comments": [],
      "createdAt": "2026-07-12",
      "tags": []
    }
  ]
}
];

// Seed classification: the imported tasks arrive untagged, so match each one to
// a module by keywords in its title/description. This tags them with the module
// name, which populates both the Modules view (via tag match) and the Tag view.
// Users can override any assignment from the Modules view's reassign dropdown.
const MODULE_KEYWORDS: { name: string; kws: string[] }[] = [
  { name: "Safety", kws: ["safety", "audit", "complian", "standard", "supervis", "inspect", "protect", "chair"] },
  { name: "3D Printing", kws: ["3d print", "3dp", "printer", "printing", "filament", "nozzle", "prusa", "g-code", "gcode", "layer height"] },
  { name: "Electronics", kws: ["sensor", "circuit", "pcb", "wiring", "power", "battery", "electr", "voltage", "relay", "microcontroller", "esp", "arduino", "transceiver", "radio", "inverter", "motor", "coil", "pid", "controller", "data logger", "tesla", "ece", "robotino", "measurement", "thermal device", "monitoring"] },
  { name: "Fabrication", kws: ["fabricat", "manfact", "manufact", "weld", "laser", "cnc", "assembly", "chassis", "mount", "frame", "cad", "machin", "workshop", "workbench", "router", "foam", "cutting", "shaker", "hpde"] },
  { name: "Software", kws: ["dashboard", "firmware", "software", "api", "database", "script", "cloud", "automat", "email", "kpi", "form", "odoo", "gamification", "visualizer", "decision log", "linkedin", "content", "report", "system", "web-kit", "kit"] },
];

INITIAL_PROJECTS.forEach((p) => {
  const modNames = new Set((p.modules || []).map((m) => m.name));
  if (modNames.size === 0) return;
  p.tasks.forEach((t) => {
    if (t.tags && t.tags.length > 0) return;
    const hay = (t.title + " " + (t.description || "")).toLowerCase();
    for (const g of MODULE_KEYWORDS) {
      if (modNames.has(g.name) && g.kws.some((k) => hay.includes(k))) {
        t.tags = [g.name];
        break;
      }
    }
  });
});

export const TEAM_MEMBERS = [
  "Abdallah",
  "Sallam",
  "Unassigned",
  "Alice",
  "Bob",
  "Charlie",
  "Diana"
];

export const PRIORITIES: { value: "low" | "medium" | "high" | "urgent"; label: string; color: string; bg: string }[] = [
  { value: "low", label: "Low", color: "#94a3b8", bg: "bg-slate-800/60 text-slate-300 border-slate-700" },
  { value: "medium", label: "Medium", color: "#3b82f6", bg: "bg-blue-500/10 text-blue-400 border-blue-500/20" },
  { value: "high", label: "High", color: "#f59e0b", bg: "bg-amber-500/10 text-amber-400 border-amber-500/20" },
  { value: "urgent", label: "Critical", color: "#f43f5e", bg: "bg-red-500/10 text-red-400 border-red-500/20" },
];

// Engineering readiness lifecycle for a module (subsystem)
export const MODULE_READINESS: { value: ModuleReadiness; label: string; color: string }[] = [
  { value: "design", label: "Design", color: "#64748b" },
  { value: "prototype", label: "Prototype", color: "#6366f1" },
  { value: "bench-test", label: "Bench-test", color: "#f59e0b" },
  { value: "integrated", label: "Integrated", color: "#3b82f6" },
  { value: "done", label: "Done", color: "#10b981" },
];
